/**
 * Turn the vendored woff2 files into a generated ES module of data URIs.
 *
 * The widget is dropped into a CMS with one script tag, so a relative font URL
 * is a deployment hazard: it has to resolve from wherever the bundle happens to
 * be served, and in the IIFE build there is no import.meta.url to resolve it
 * against. Inlining removes the whole class of problem, at the cost of ~40 kB
 * in the bundle, and means the first paint already has the right font.
 *
 * Run with: node scripts/build-fonts.mjs
 * The output is committed so that src/ works with no build step at all.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const faces = [
  {
    name: 'latin',
    file: `${here}../src/assets/fonts/figtree-latin.woff2`,
    range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  },
  {
    name: 'latin-ext',
    file: `${here}../src/assets/fonts/figtree-latin-ext.woff2`,
    range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
  },
];

const body = faces.map(({ name, file, range }) => {
  const base64 = readFileSync(file).toString('base64');
  return `  {
    subset: ${JSON.stringify(name)},
    src: 'url("data:font/woff2;base64,${base64}") format("woff2")',
    unicodeRange: ${JSON.stringify(range)},
  },`;
}).join('\n');

const out = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
// Figtree (SIL Open Font License 1.1), subset by Google Fonts.
export const FIGTREE_FACES = [
${body}
];
`;

writeFileSync(`${here}../src/assets/fonts.js`, out);
console.log(`wrote src/assets/fonts.js (${(out.length / 1024).toFixed(1)} kB)`);
