#!/usr/bin/env node
/**
 * Render the widget at the widths that matter and write them out for review.
 *
 * Run: npm run qa
 *
 * This used to diff the render against the Canva export. That made sense while
 * the job was reproducing it; the design is ours now, so a pixel diff against
 * the old file would only measure how far we have deliberately moved. What is
 * worth checking automatically is what the *rules* promise: that type never
 * drops below the readable floor, that nothing overflows its card, and that the
 * connector tree still lands on the boxes. Those are asserted here and in
 * tests/e2e; the screenshots are for the eye.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { withWidget, openWidget } from './render.mjs';
import { STACK_BELOW } from '../src/tokens.js';

const QA = fileURLToPath(new URL('../docs/qa/', import.meta.url));

const WIDTHS = [
  { width: 1850, name: 'wide', note: 'full-width embed' },
  { width: 1440, name: 'desktop', note: 'typical desktop page' },
  { width: 1200, name: 'laptop', note: `below ${STACK_BELOW}px — stacked` },
  { width: 768, name: 'tablet', note: 'stacked' },
  { width: 390, name: 'phone', note: 'stacked' },
];

/** Minimum font size anywhere in the widget, and anything wider than its card. */
const audit = (page) => page.locator('stefnu-rit').evaluate((el) => {
  const root = el.shadowRoot;
  const sizes = [...root.querySelectorAll('.label, .card-title, .pill')]
    .map((n) => parseFloat(getComputedStyle(n).fontSize));

  const overflowing = [];
  for (const card of root.querySelectorAll('.card')) {
    const box = card.getBoundingClientRect();
    for (const label of card.querySelectorAll('.label')) {
      const r = label.getBoundingClientRect();
      // 1px of slack for sub-pixel rounding.
      if (r.right > box.right + 1 || r.left < box.left - 1) {
        overflowing.push(label.textContent.trim().slice(0, 40));
      }
    }
  }

  const lines = [...root.querySelectorAll('.lines line')].map((l) => l.dataset.role);
  return {
    minFontSize: sizes.length ? Math.min(...sizes) : null,
    overflowing,
    lines: lines.reduce((acc, role) => ({ ...acc, [role]: (acc[role] ?? 0) + 1 }), {}),
    height: Math.round(el.getBoundingClientRect().height),
  };
});

await mkdir(QA, { recursive: true });

const rows = [];
let failed = false;

await withWidget(async ({ browser, origin }) => {
  for (const { width, name, note } of WIDTHS) {
    const { page, messages } = await openWidget(browser, origin, width);
    await page.locator('stefnu-rit').screenshot({ path: `${QA}${name}-${width}.png` });
    const result = await audit(page);
    await page.close();

    const problems = [];
    if (result.minFontSize !== null && result.minFontSize < 15) {
      problems.push(`text down to ${result.minFontSize}px`);
    }
    if (result.overflowing.length) {
      problems.push(`${result.overflowing.length} label(s) outside their card: ${result.overflowing.join('; ')}`);
    }
    if (messages.length) problems.push(`console: ${messages.join(' / ')}`);
    if (problems.length) failed = true;

    rows.push({ width, name, note, ...result, problems });
    console.log(
      `${String(width).padStart(5)}px  ${name.padEnd(8)} ${String(result.height).padStart(5)}px tall  ` +
      `min ${result.minFontSize}px  lines ${JSON.stringify(result.lines)}  ` +
      (problems.length ? `⚠️  ${problems.join('; ')}` : 'ok'),
    );
  }
});

const report = `# Rendered widths

Generated by \`npm run qa\` on ${new Date().toISOString().slice(0, 10)}.

The design is the project's own; it is no longer compared against the Canva
export it started from. What is checked here is what the layout rules promise.

| Width | Layout | Height | Smallest text | Connectors | |
|---|---|---|---|---|---|
${rows.map((r) => `| ${r.width}px | ${r.note} | ${r.height}px | ${r.minFontSize}px | ${Object.entries(r.lines).map(([k, v]) => `${v}×${k}`).join(', ') || '—'} | ${r.problems.length ? '⚠️ ' + r.problems.join('; ') : 'ok'} |`).join('\n')}

Body text never drops below 15px: the type scale is fluid between a readable
floor and the size the original used at full width, rather than shrinking in
proportion to the widget.

The column tree needs about ${STACK_BELOW}px — five columns wide enough that
"Upplýsingaöryggisstefna" sits on one line. Chromium has no Icelandic
hyphenation patterns, so a narrower column would have to break compounds
mid-syllable. Below that width the layout stacks instead, keeping to a readable
measure with the rail in its own gutter.

## Screenshots

${rows.map((r) => `- \`${r.name}-${r.width}.png\` — ${r.note}`).join('\n')}
`;

await writeFile(`${QA}README.md`, report);
console.log(`\nwrote docs/qa/README.md and ${rows.length} screenshots`);
if (failed) process.exitCode = 1;
